// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5a9naSTTC6uBoWo_9VaJt2wqriJfnqT4',
    appId: '1:69643858080:web:6d341f9931f1c844bd19c5',
    messagingSenderId: '69643858080',
    projectId: 'rx-quiz-c7d47',
    authDomain: 'rx-quiz-c7d47.firebaseapp.com',
    storageBucket: 'rx-quiz-c7d47.firebasestorage.app',
    measurementId: 'G-P0XTNE22CF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxN4NsfKkrGNbok0jYZRSBaejq7GzwvIo',
    appId: '1:69643858080:android:8eef8341584c2098bd19c5',
    messagingSenderId: '69643858080',
    projectId: 'rx-quiz-c7d47',
    storageBucket: 'rx-quiz-c7d47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvTZMCRxSd-myPU1_FzlQY64duD97G6kU',
    appId: '1:69643858080:ios:11ea5575a2993416bd19c5',
    messagingSenderId: '69643858080',
    projectId: 'rx-quiz-c7d47',
    storageBucket: 'rx-quiz-c7d47.firebasestorage.app',
    iosBundleId: 'com.example.monami',
  );
}
